# Generated by Django 4.0 on 2022-01-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='teach_certificate',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teach_idcard',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teach_licences',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='teach_vedio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='majorproject',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
