# Generated by Django 4.0 on 2022-01-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacherinfo_teach_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilinginformation',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
