# Generated by Django 4.0 on 2022-01-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_bilinginformation_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teachavailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='teachavailability',
            name='hour',
        ),
        migrations.AddField(
            model_name='teachavailability',
            name='availability',
            field=models.ManyToManyField(to='teacher.SelectField'),
        ),
    ]
