# Generated by Django 4.0 on 2022-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_selectfield_remove_teachavailability_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectfield',
            name='time',
            field=models.TimeField(),
        ),
    ]
