# Generated by Django 4.0 on 2022-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_selectfield_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectfield',
            name='day',
        ),
        migrations.RemoveField(
            model_name='selectfield',
            name='time',
        ),
        migrations.RemoveField(
            model_name='teachavailability',
            name='user',
        ),
        migrations.AddField(
            model_name='selectfield',
            name='hour',
            field=models.CharField(choices=[('1', '07:00 AM'), ('2', '08:00 AM'), ('3', '09:00 AM'), ('4', '10:00 AM'), ('5', '11:00 AM'), ('6', '12:00 PM'), ('7', '01:00 PM'), ('8', '02:00 PM'), ('9', '03:00 PM'), ('10', '04:00 PM'), ('11', '05:00 PM'), ('12', '06:00 PM')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachavailability',
            name='day',
            field=models.CharField(choices=[('0', 'SUN'), ('1', 'MON'), ('2', 'TUS'), ('3', 'WED'), ('4', 'THU'), ('5', 'FRI'), ('6', 'SAT')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
