# Generated by Django 4.0 on 2022-01-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_gender_alter_user_user_role'),
        ('teacher', '0007_remove_selectfield_day_remove_selectfield_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachavailability',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teach_availability', to='user.user'),
            preserve_default=False,
        ),
    ]
