# Generated by Django 4.0 on 2021-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_role', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=19)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=55)),
                ('otp', models.CharField(max_length=20)),
                ('otp_is_verified', models.BooleanField(default=False)),
                ('otp_is_expired', models.DateTimeField(null=True)),
                ('image', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=19)),
            ],
        ),
    ]
