# Generated by Django 4.0 on 2021-12-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
