# Generated by Django 4.0 on 2022-01-03 07:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_gender_alter_user_image_alter_user_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, user.models.GenderEnum['Male']), (2, user.models.GenderEnum['Female'])], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[(1, user.models.UserRoleEnum['Teacher']), (2, user.models.UserRoleEnum['Student'])], max_length=19),
        ),
    ]
